sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: nFEEt0/oC0QzpE8zzBLnJ8BCZGYXAxmDM+RSg6ih6+B/4jt3dvoVYIrtA8HeLLJLUcBtf9h0c0I5tvRJ5liqJXAM2m3aTdE04Lt8zRgKl3yc8NnYnkq/9XQALej7nwysnlClk+sTngIqiJhl0HYWdntywqXBqk72A7OcXRmGDkXXQOZz4+zODLE02R3ffLO1q49c8aARGMx0a+vNudek7vfwhcCGaohavIZoCoEc5GiR0FCJzqNbM+X++4Pc9YrqKyOQPgHqOuFq9p7UeoLIE9BQ18nGo3qH1bThLLS3FLM2O6bAFWjv0KmJle38F93rdJFEb1tEoWOKYlylwAW7kWKwJr5KL1gXXl6KnOchAzqQvUcmoyfl+XtezBLaLVzJDWDyjaNXaMklv8WvitsymUYx0A4zMcgm3Tn+TbNlfWfIEc2ZorkJOtmplCEs56KGzjw2+k7Fg0yRMh9OYsZ3khN8DxHODxM5oMANBXuCG2CJKmT6dHRKgkOl6Fwyc15Uogu2AJ9MnKqbawBhRBbVmH1XoU+oXD0GC0a5bvQXM0fLyGnVUi2s/QnNCgI2BDqyu6Bbr7ByeDnrhUJVESoBp0B6Q2kON5egxLsk3wVuNAztwZ3vxK40hEZjpUGF9q5ZM1iE3+mfGtAt5FQsuoFKW1Zud49lkLwvJps2DjRxeCI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Tales-and-Novels-of-J-de-La-Fontaine-Volume-21_5295
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy